def getEmployee(id: Int)(using ec: ExecutionContext): Future[Employee] = ...
def getRole(employee: Employee)(using ec: ExecutionContext): Future[Role] = ...

given executionContext: ExecutionContext = ...

val bigEmployee: Future[EmployeeWithRole] =
  getEmployee(100).flatMap(e => getRole(e).map(r => EmployeeWithRole(e, r)))
